Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/argentina/ir2/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/overview2/vis/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 76, in updateLatest
    imagesDownloader(images_url,1)
  File "/home/guido/scripts/imagesDownloader.py", line 117, in imagesDownloader
    new_latest.write("Initial file")
  File "/usr/lib/python2.7/filecmp.py", line 43, in cmp
    s2 = _sig(os.stat(f2))
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/baja/ir3/remote_latest.info'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 76, in updateLatest
    imagesDownloader(images_url,1)
  File "/home/guido/scripts/imagesDownloader.py", line 119, in imagesDownloader
    files_cmp = filecmp.cmp(images_root + subpath + 'latest.info',images_root + subpath + 'remote_latest.info' )
  File "/usr/lib/python2.7/filecmp.py", line 43, in cmp
    s2 = _sig(os.stat(f2))
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/brazil/ir2_2/remote_latest.info'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 76, in updateLatest
    imagesDownloader(images_url,1)
  File "/home/guido/scripts/imagesDownloader.py", line 119, in imagesDownloader
    files_cmp = filecmp.cmp(images_root + subpath + 'latest.info',images_root + subpath + 'remote_latest.info' )
  File "/usr/lib/python2.7/filecmp.py", line 43, in cmp
    s2 = _sig(os.stat(f2))
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/california/ir4/remote_latest.info'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 76, in updateLatest
    imagesDownloader(images_url,1)
  File "/home/guido/scripts/imagesDownloader.py", line 119, in imagesDownloader
    files_cmp = filecmp.cmp(images_root + subpath + 'latest.info',images_root + subpath + 'remote_latest.info' )
  File "/usr/lib/python2.7/filecmp.py", line 43, in cmp
    s2 = _sig(os.stat(f2))
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/mexico_north/ir2/remote_latest.info'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 76, in updateLatest
    imagesDownloader(images_url,1)
  File "/home/guido/scripts/imagesDownloader.py", line 119, in imagesDownloader
    files_cmp = filecmp.cmp(images_root + subpath + 'latest.info',images_root + subpath + 'remote_latest.info' )
  File "/usr/lib/python2.7/filecmp.py", line 43, in cmp
    s2 = _sig(os.stat(f2))
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/new_england/ir4/remote_latest.info'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/overview2/vis/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/overview2/vis/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    os.remove(images_root + subpath + str(i) + '.jpg')
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/overview2/vis/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 65, in updateLatest
    try:
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/overview2/vis/19.jpg'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 79, in updateLatest
    imagesDownloader(images_url,1)
  File "/home/guido/scripts/imagesDownloader.py", line 122, in imagesDownloader
    files_cmp = filecmp.cmp(images_root + subpath + 'latest.info',images_root + subpath + 'remote_latest.info' )
  File "/usr/lib/python2.7/filecmp.py", line 43, in cmp
    s2 = _sig(os.stat(f2))
OSError: [Errno 2] No such file or directory: '/var/www/clouds/img/goeseast/venezuela/ir3/remote_latest.info'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 79, in updateLatest
    imagesDownloader(images_url,1)
  File "/home/guido/scripts/imagesDownloader.py", line 99, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 113] No route to host>
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 24, in update
    response = urlopen(level1_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 13, in update
    response = urlopen(root_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 13, in update
    response = urlopen(root_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 75, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 77, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 128, in imagesDownloader
    for trs in reversed (soup.findAll('a'))[-totalImages -1:]:
TypeError: 'listreverseiterator' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 128, in imagesDownloader
    for trs in reversed (soup.findAll('a'))[-totalImages -1:]:
TypeError: 'listreverseiterator' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 128, in imagesDownloader
    for trs in reversed (soup.findAll('a'))[-totalImages -1:]:
TypeError: 'listreverseiterator' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 128, in imagesDownloader
    for trs in reversed (soup.findAll('a'))[-totalImages -1:]:
TypeError: 'listreverseiterator' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 70, in updateLatest
    logger.info(i + '.jpg  doesnt exist')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 81, in updateLatest
    imagesDownloader(images_url,1)
  File "/home/guido/scripts/imagesDownloader.py", line 113, in imagesDownloader
    html = response.read()
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 543, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 612, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/usr/lib/python2.7/httplib.py", line 660, in _safe_read
    raise IncompleteRead(''.join(s), amt)
httplib.IncompleteRead: IncompleteRead(3389 bytes read, 2226 more expected)
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 24, in update
    response = urlopen(level1_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 13, in update
    response = urlopen(root_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',1)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',1)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',1)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',1)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 33, in update
    imagesDownloader.updateLatest(level2_url)
  File "/home/guido/scripts/imagesDownloader.py", line 81, in updateLatest
    imagesDownloader(images_url,1)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 5, in <module>
    imagesUpdate.update()
  File "/home/guido/scripts/imagesUpdate.py", line 24, in update
    response = urlopen(level1_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/guido/scripts/imagesUpdater.py", line 2, in <module>
    import sys, time, imagesUpdate
  File "/home/guido/scripts/imagesUpdate.py", line 2, in <module>
    import imagesDownloader
  File "/home/guido/scripts/imagesDownloader.py", line 163, in <module>
    imagesDownloader('http://goes.gsfc.nasa.gov/goeseast/argentina/ir4/',20)
  File "/home/guido/scripts/imagesDownloader.py", line 101, in imagesDownloader
    response = urlopen(images_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
